/** Choose copy for a token generated by Better Auth; never used for authorization. */
export function getVerificationEmailPurpose(
	token: string,
	requestUrl?: string,
): "registration" | "email-change" {
	// Unverified self-hosted accounts can change their address before receiving
	// a normal verification token. In that case the token has no updateTo claim.
	if (requestUrl && new URL(requestUrl).pathname.endsWith("/change-email")) {
		return "email-change";
	}
	try {
		const payload = JSON.parse(
			Buffer.from(token.split(".")[1] ?? "", "base64url").toString("utf8"),
		);
		if (typeof payload?.updateTo === "string" && payload.updateTo) {
			return "email-change";
		}
	} catch {
		// Presentation can fall back to standard verification copy. Better Auth
		// independently validates the token when the recipient follows the link.
	}
	return "registration";
}
