import { randomUUID } from "node:crypto";
import { constants } from "node:fs";
import { lstat, mkdir, open, realpath, rename, unlink } from "node:fs/promises";
import { dirname, isAbsolute, join } from "node:path";
import { setTimeout as delay } from "node:timers/promises";

function hasCode(error: unknown, code: string) {
	return error instanceof Error && "code" in error && error.code === code;
}

function validateKey(key: string) {
	// Keys are generated by the server, never interpreted as OS paths.
	if (
		!key ||
		key
			.split("/")
			.some(
				(part) =>
					!/^[a-zA-Z0-9][a-zA-Z0-9._-]*$/u.test(part) ||
					part.endsWith(".") ||
					/^(con|prn|aux|nul|com[1-9]|lpt[1-9])(?:\.|$)/iu.test(part),
			)
	) {
		throw new Error("Invalid filesystem object key.");
	}
}

async function objectPath(root: string, key: string, create: boolean) {
	validateKey(key);
	if (!isAbsolute(root))
		throw new Error("Filesystem storage path must be absolute.");
	if (create) await mkdir(root, { recursive: true, mode: 0o700 });
	// The configured root may be a mounted dataset or an operator-owned symlink.
	let directory = await realpath(root);
	const parts = key.split("/");
	for (const part of parts.slice(0, -1)) {
		directory = join(directory, part);
		if (create) {
			await mkdir(directory, { mode: 0o700 }).catch((error) => {
				if (!hasCode(error, "EEXIST")) throw error;
			});
		}
		const stat = await lstat(directory);
		if (stat.isSymbolicLink() || !stat.isDirectory()) {
			throw new Error("Filesystem object directories must not be symlinks.");
		}
	}
	const target = join(directory, parts[parts.length - 1]);
	const stat = await lstat(target).catch((error) => {
		if (hasCode(error, "ENOENT")) return null;
		throw error;
	});
	if (stat && (stat.isSymbolicLink() || !stat.isFile())) {
		throw new Error("Filesystem objects must be regular files.");
	}
	return target;
}

export async function putFilesystemObject(
	root: string,
	key: string,
	body: Uint8Array,
) {
	const target = await objectPath(root, key, true);
	const temporary = join(dirname(target), `.upload-${randomUUID()}`);
	const file = await open(temporary, "wx", 0o600);
	try {
		try {
			await file.writeFile(body);
			await file.sync();
		} finally {
			await file.close();
		}
		// Readers see either the complete old object or the complete new object.
		for (let attempt = 0; ; attempt++) {
			try {
				await rename(temporary, target);
				break;
			} catch (error) {
				// Windows readers/virus scanners may briefly hold a replacement lock.
				if (
					process.platform !== "win32" ||
					attempt >= 6 ||
					(!hasCode(error, "EPERM") &&
						!hasCode(error, "EACCES") &&
						!hasCode(error, "EBUSY"))
				)
					throw error;
				await delay(10 * 2 ** attempt);
			}
		}
	} finally {
		await unlink(temporary).catch((error) => {
			if (!hasCode(error, "ENOENT")) throw error;
		});
	}
}

export async function getFilesystemObject(root: string, key: string) {
	try {
		const target = await objectPath(root, key, false);
		const file = await open(
			target,
			constants.O_RDONLY | (constants.O_NOFOLLOW ?? 0),
		);
		try {
			return new Uint8Array(await file.readFile());
		} finally {
			await file.close();
		}
	} catch (error) {
		if (!hasCode(error, "ENOENT")) throw error;
		const missing = new Error("Filesystem object not found.");
		missing.name = "NoSuchKey";
		throw missing;
	}
}

export async function deleteFilesystemObject(root: string, key: string) {
	try {
		await unlink(await objectPath(root, key, false));
	} catch (error) {
		if (!hasCode(error, "ENOENT")) throw error;
	}
}

export async function checkFilesystemStorage(root: string) {
	const key = `checks/${randomUUID()}`;
	const bytes = new Uint8Array([115, 107, 101, 100, 114, 97]);
	try {
		await putFilesystemObject(root, key, bytes);
		const stored = await getFilesystemObject(root, key);
		if (!Buffer.from(stored).equals(bytes)) {
			throw new Error("Filesystem storage verification failed.");
		}
	} finally {
		await deleteFilesystemObject(root, key);
	}
}
