import assert from "node:assert/strict";
import { test } from "node:test";
import {
	buildTemplateSectionLayoutSyncUpdates,
	createCanvasTemplateElements,
	createCanvasTemplateStickyNote,
	getTemplateSectionMeta,
} from "./templates";

function defaults() {
	let index = 0;
	return {
		createId: () => `id-${index++}`,
		stroke: "#111",
		fontFamily: "Inter",
		kanbanFontFamily: "Inter",
	};
}

test("all public templates are generated by the shared factory", () => {
	for (const id of [
		"kanban",
		"mindmap",
		"flowchart",
		"retrospective",
		"swot",
	] as const) {
		const elements = createCanvasTemplateElements({
			id,
			x: 100,
			y: 100,
			defaults: defaults(),
		});
		assert.ok(elements.length > 0, `${id} must contain elements`);
	}
});

test("template sticky placement and section layout share one implementation", () => {
	const factoryDefaults = defaults();
	const template = createCanvasTemplateElements({
		id: "retrospective",
		x: 0,
		y: 0,
		defaults: factoryDefaults,
	});
	const section = template.find((element) => getTemplateSectionMeta(element));
	assert.ok(section);
	const allElements = [...template];
	let note = null;
	for (let index = 0; index < 7; index++) {
		note = createCanvasTemplateStickyNote({
			defaults: factoryDefaults,
			section,
			existingElements: allElements,
			text: `Shared note ${index}`,
		});
		assert.ok(note);
		allElements.push(note);
	}
	const elements = new Map(allElements.map((element) => [element.id, element]));
	const updates = buildTemplateSectionLayoutSyncUpdates(elements);
	assert.ok(updates.some((update) => update.id === section.id));
	assert.equal(note?.frameId, section.id);
});
