import assert from "node:assert/strict";
import { test } from "node:test";
import {
	buildTemplateSectionLayoutSyncUpdates,
	createCanvasTemplateElements,
	createCanvasTemplateStickyNote,
	getTemplateSectionMeta,
} from "./templates";
import { getWireframeElementMeta } from "./wireframe";

function defaults() {
	let index = 0;
	return {
		createId: () => `id-${index++}`,
		stroke: "#111",
		fontFamily: "Inter",
		kanbanFontFamily: "Inter",
	};
}

test("all public templates are generated by the shared factory", () => {
	for (const id of [
		"kanban",
		"gantt",
		"mindmap",
		"flowchart",
		"retrospective",
		"swot",
		"wireframe",
	] as const) {
		const elements = createCanvasTemplateElements({
			id,
			x: 100,
			y: 100,
			defaults: defaults(),
		});
		assert.ok(elements.length > 0, `${id} must contain elements`);
	}
});

test("wireframe template stores responsive screens and components as canvas elements", () => {
	const elements = createCanvasTemplateElements({
		id: "wireframe",
		x: 0,
		y: 0,
		defaults: defaults(),
	});
	const screens = elements.filter(
		(element) => element.customData?.skedraType === "wireframe-screen",
	);
	const nodes = elements.filter(
		(element) => element.customData?.skedraType === "wireframe-node",
	);
	assert.equal(screens.length, 2);
	assert.ok(nodes.length > 20);
	assert.deepEqual(
		screens.map((screen) => screen.customData?.wireframeViewport).sort(),
		["desktop", "mobile"],
	);
	const screenIds = new Set(screens.map((screen) => screen.id));
	assert.ok(nodes.every((node) => node.frameId && screenIds.has(node.frameId)));
	assert.ok(nodes.every((node) => node.groupId));
	assert.ok(
		nodes.every((node) => !("wireframeScreenId" in (node.customData ?? {}))),
	);
	assert.ok(
		nodes.every(
			(node) =>
				getWireframeElementMeta(node)?.wireframeScreenId === node.frameId,
		),
	);
});

test("template sticky placement and section layout share one implementation", () => {
	const factoryDefaults = defaults();
	const template = createCanvasTemplateElements({
		id: "retrospective",
		x: 0,
		y: 0,
		defaults: factoryDefaults,
	});
	const section = template.find((element) => getTemplateSectionMeta(element));
	assert.ok(section);
	const allElements = [...template];
	let note = null;
	for (let index = 0; index < 7; index++) {
		note = createCanvasTemplateStickyNote({
			defaults: factoryDefaults,
			section,
			existingElements: allElements,
			text: `Shared note ${index}`,
		});
		assert.ok(note);
		allElements.push(note);
	}
	const elements = new Map(allElements.map((element) => [element.id, element]));
	const updates = buildTemplateSectionLayoutSyncUpdates(elements);
	assert.ok(updates.some((update) => update.id === section.id));
	assert.equal(note?.frameId, section.id);
});

test("SWOT layout normalization is idempotent", () => {
	const template = createCanvasTemplateElements({
		id: "swot",
		x: 0,
		y: 0,
		defaults: defaults(),
	});
	const elements = new Map(template.map((element) => [element.id, element]));
	const strengths = template.find(
		(element) =>
			getTemplateSectionMeta(element)?.templateSectionId === "strengths",
	);
	assert.ok(strengths);
	elements.set(strengths.id, {
		...strengths,
		height: strengths.height + 100,
	});

	const firstUpdates = buildTemplateSectionLayoutSyncUpdates(elements);
	assert.ok(firstUpdates.length > 0);
	for (const update of firstUpdates) {
		const current = elements.get(update.id);
		if (current) elements.set(update.id, { ...current, ...update.changes });
	}

	assert.deepEqual(buildTemplateSectionLayoutSyncUpdates(elements), []);
});

test("growing template notes retain their height, avoid overlap and leave room for the add action", () => {
	for (const id of ["retrospective", "swot"] as const) {
		const factory = defaults();
		const template = createCanvasTemplateElements({
			id,
			x: 0,
			y: 0,
			defaults: factory,
		});
		const section = template.find((element) => getTemplateSectionMeta(element));
		assert.ok(section);
		const all = [...template];
		for (let index = 0; index < 5; index++) {
			const note = createCanvasTemplateStickyNote({
				defaults: factory,
				section,
				existingElements: all,
				text: "A longer thought",
			});
			assert.ok(note);
			if (index === 0) note.height = 270;
			all.push(note);
		}
		const elements = new Map(all.map((element) => [element.id, element]));
		for (const update of buildTemplateSectionLayoutSyncUpdates(elements)) {
			const current = elements.get(update.id);
			if (current) elements.set(update.id, { ...current, ...update.changes });
		}
		const notes = [...elements.values()].filter(
			(element) => element.frameId === section.id,
		);
		assert.equal(notes[0].height, 270);
		assert.ok(notes[2].y >= notes[0].y + notes[0].height + 18);
		const bottom = Math.max(...notes.map((note) => note.y + note.height));
		const frame = elements.get(section.id);
		assert.ok(frame);
		assert.ok(frame.y + frame.height - bottom >= 60);
		assert.deepEqual(buildTemplateSectionLayoutSyncUpdates(elements), []);
	}
});

test("SWOT axes match positive and negative columns and internal and external rows", () => {
	const template = createCanvasTemplateElements({
		id: "swot",
		x: 0,
		y: 0,
		defaults: defaults(),
	});
	const role = (name: string) => {
		const element = template.find(
			(element) => element.customData?.templateLayoutRole === name,
		);
		assert.ok(element);
		return element;
	};
	assert.equal(role("label-support").x, role("strengths").x);
	assert.equal(role("label-risk").x, role("weaknesses").x);
	assert.ok(role("label-internal").y > role("strengths").y);
	assert.ok(role("label-internal").y < role("opportunities").y);
	assert.ok(role("label-external").y > role("opportunities").y);
});
