import {
	type CanvasElement,
	type CanvasElementFactoryDefaults,
	createCanvasElementFromBoundsInput,
} from "@skedra/canvas-core";
import { canvasBoundsElementInputSchema } from "@skedra/shared";
import { z } from "zod";

/**
 * MCP canvas input with the complete safe visual surface.
 *
 * `zIndex` is deliberately semantic and batch-local. Persistent stack indexes
 * are generated by the server against the current board state, so agents never
 * need to construct Skedra's opaque `stackIndex` values themselves.
 */
export const elementInputSchema = canvasBoundsElementInputSchema
	.extend({
		zIndex: z
			.number()
			.int()
			.min(-10_000)
			.max(10_000)
			.optional()
			.describe(
				"Layer innerhalb dieses Batches: kleinere Werte liegen hinten, groessere vorne.",
			),
	})
	.strict();

export type McpCanvasElementInput = z.infer<typeof elementInputSchema>;

/** Stable batch ordering: zIndex first, original request order as tie-breaker. */
export function orderMcpCanvasElementInputs(
	inputs: readonly McpCanvasElementInput[],
): McpCanvasElementInput[] {
	return inputs
		.map((input, requestIndex) => ({ input, requestIndex }))
		.sort(
			(left, right) =>
				(left.input.zIndex ?? 0) - (right.input.zIndex ?? 0) ||
				left.requestIndex - right.requestIndex,
		)
		.map(({ input }) => input);
}

/** Converts the bounds-oriented MCP shape contract into a renderable element. */
export function createMcpCanvasElement(
	defaults: CanvasElementFactoryDefaults,
	input: McpCanvasElementInput,
): CanvasElement {
	return createCanvasElementFromBoundsInput(defaults, input, {
		createPathPointsFromBounds: true,
	});
}
